name             'efg'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures efg'
long_description 'Installs/Configures efg'
version          '0.11.0'

depends 'chef-client'
depends 'database'
depends 'fail2ban'
depends 'openssh'
depends 'mysql', '~> 5.6.1'
depends 'mysql-chef_gem', '~> 0.0.5'
depends 'passenger_nginx'
depends 'jenkins'
depends 'sudo'
depends 'users'
depends 'hostnames'
depends 'backup'
