name             'efg'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures efg'
long_description 'Installs/Configures efg'
version          '0.5.0'
depends          'mysql'
depends          'database'
depends          'passenger_nginx'
depends          'jenkins'
